heat_template_version: 2016-04-08

description: >
  OpenStack Ceilometer Expirer service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionCeilometerExpirer:
    default: 'overcloud-ceilometer-expirer'
    type: string

resources:
  CeilometerServiceBase:
    type: ./ceilometer-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Ceilometer Expirer role.
    value:
      service_name: ceilometer_expirer
      monitoring_subscription: {get_param: MonitoringSubscriptionCeilometerExpirer}
      config_settings:
        get_attr: [CeilometerServiceBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::ceilometer::expirer
