heat_template_version: 2016-04-08

description: >
  OpenStack Cinder base service. Shared by all Cinder services.

parameters:
  CinderPassword:
    description: The password for the cinder service account, used by cinder-api.
    type: string
    hidden: true
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string

outputs:
  role_data:
    description: Role data for the Cinder base service.
    value:
      service_name: cinder_base
      config_settings:
        cinder::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://cinder:'
              - {get_param: CinderPassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/cinder'
        cinder::debug: {get_param: Debug}
        cinder::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        cinder::rabbit_userid: {get_param: RabbitUserName}
        cinder::rabbit_password: {get_param: RabbitPassword}
        cinder::rabbit_port: {get_param: RabbitClientPort}
        cinder::rabbit_heartbeat_timeout_threshold: 60
        cinder::cron::db_purge::destination: '/dev/null'
        cinder::db::database_db_max_retries: -1
        cinder::db::database_max_retries: -1
