heat_template_version: 2016-04-08

description: >
  Gnocchi service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionGnocchiStatsd:
    default: 'overcloud-gnocchi-statsd'
    type: string

resources:
  GnocchiServiceBase:
    type: ./gnocchi-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Gnocchi role.
    value:
      service_name: gnocchi_statsd
      monitoring_subscription: {get_param: MonitoringSubscriptionGnocchiStatsd}
      config_settings:
        map_merge:
          - get_attr: [GnocchiServiceBase, role_data, config_settings]
          - tripleo.gnocchi_statsd.firewall_rules:
              '140 gnocchi-statsd':
                dport: 8125
                proto: 'udp'
      step_config: |
        include ::tripleo::profile::base::gnocchi::statsd
