heat_template_version: 2016-04-08

description: >
  HAproxy service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HAProxyStatsPassword:
    description: Password for HAProxy stats endpoint
    hidden: true
    type: string
  HAProxyStatsUser:
    description: User for HAProxy stats endpoint
    default: admin
    type: string
  HAProxySyslogAddress:
    default: /dev/log
    description: Syslog address where HAproxy will send its log
    type: string
  RedisPassword:
    description: The password for Redis
    type: string
    hidden: true
  MonitoringSubscriptionHaproxy:
    default: 'overcloud-haproxy'
    type: string

outputs:
  role_data:
    description: Role data for the HAproxy role.
    value:
      service_name: haproxy
      monitoring_subscription: {get_param: MonitoringSubscriptionHaproxy}
      config_settings:
        tripleo.haproxy.firewall_rules:
          '107 haproxy stats':
            dport: 1993
        tripleo::haproxy::haproxy_log_address: {get_param: HAProxySyslogAddress}
        tripleo::haproxy::haproxy_stats_user: {get_param: HAProxyStatsUser}
        tripleo::haproxy::haproxy_stats_password: {get_param: HAProxyStatsPassword}
        tripleo::haproxy::redis_password: {get_param: RedisPassword}
      step_config: |
        include ::tripleo::profile::base::haproxy
