heat_template_version: 2016-04-08

description: >
  Openstack Heat CloudFormation API service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HeatWorkers:
    default: 0
    description: Number of workers for Heat service.
    type: number
  HeatPassword:
    description: The password for the Heat service and db account, used by the Heat services.
    type: string
    hidden: true
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint
  MonitoringSubscriptionHeatApiCnf:
    default: 'overcloud-heat-api-cfn'
    type: string
  HeatApiCfnLoggingSource:
    type: json
    default:
      tag: openstack.heat.api.cfn
      path: /var/log/heat/heat-api-cfn.log

resources:
  HeatBase:
    type: ./heat-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Heat CloudFormation API role.
    value:
      service_name: heat_api_cfn
      monitoring_subscription: {get_param: MonitoringSubscriptionHeatApiCnf}
      logging_source: {get_param: HeatApiCfnLoggingSource}
      logging_groups:
        - heat
      config_settings:
        map_merge:
          - get_attr: [HeatBase, role_data, config_settings]
          - heat::api_cfn::workers: {get_param: HeatWorkers}
            tripleo.heat_api_cfn.firewall_rules:
              '125 heat_cfn':
                dport:
                  - 8000
                  - 13800
            # NOTE: bind IP is found in Heat replacing the network name with the
            # local node IP for the given network; replacement examples
            # (eg. for internal_api):
            # internal_api -> IP
            # internal_api_uri -> [IP]
            # internal_api_subnet - > IP/CIDR
            heat::api_cfn::bind_host: {get_param: [ServiceNetMap, HeatApiNetwork]}
      step_config: |
        include ::tripleo::profile::base::heat::api_cfn
      service_config_settings:
        keystone:
          map_merge:
            - get_attr: [HeatBase, role_data, service_config_settings, keystone]
            - heat::keystone::auth_cfn::tenant: 'service'
              heat::keystone::auth_cfn::public_url: {get_param: [EndpointMap, HeatCfnPublic, uri]}
              heat::keystone::auth_cfn::internal_url: {get_param: [EndpointMap, HeatCfnInternal, uri]}
              heat::keystone::auth_cfn::admin_url: {get_param: [EndpointMap, HeatCfnAdmin, uri]}
              heat::keystone::auth_cfn::password: {get_param: HeatPassword}
              heat::keystone::auth_cfn::region: {get_param: KeystoneRegion}
