heat_template_version: 2016-04-08

description: >
  Openstack Heat CloudWatch API service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HeatWorkers:
    default: 0
    description: Number of workers for Heat service.
    type: number
  MonitoringSubscriptionHeatApiCloudwatch:
    default: 'overcloud-heat-api-cloudwatch'
    type: string
  HeatApiCloudwatchLoggingSource:
    type: json
    default:
      tag: openstack.heat.api.cloudwatch
      path: /var/log/heat/heat-api-cloudwatch.log

resources:
  HeatBase:
    type: ./heat-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Heat Cloudwatch API role.
    value:
      service_name: heat_api_cloudwatch
      monitoring_subscription: {get_param: MonitoringSubscriptionHeatApiCloudwatch}
      logging_source: {get_param: HeatApiCloudwatchLoggingSource}
      logging_groups:
        - heat
      config_settings:
        map_merge:
          - get_attr: [HeatBase, role_data, config_settings]
          - heat::api_cloudwatch::workers: {get_param: HeatWorkers}
            tripleo.heat_api_cloudwatch.firewall_rules:
              '125 heat_cloudwatch':
                dport:
                  - 8003
                  - 13003
            # NOTE: bind IP is found in Heat replacing the network name with the
            # local node IP for the given network; replacement examples
            # (eg. for internal_api):
            # internal_api -> IP
            # internal_api_uri -> [IP]
            # internal_api_subnet - > IP/CIDR
            heat::api_cloudwatch::bind_host: {get_param: [ServiceNetMap, HeatApiNetwork]}
      step_config: |
        include ::tripleo::profile::base::heat::api_cloudwatch
