heat_template_version: 2016-04-08

description: >
  OpenStack Ironic services configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  IronicPassword:
    description: The password for the Ironic service and db account, used by the Ironic services
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string

outputs:
  role_data:
    description: Role data for the Ironic role.
    value:
      service_name: ironic_base
      config_settings:
        ironic::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://ironic:'
              - {get_param: IronicPassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/ironic'
        ironic::debug: {get_param: Debug}
        ironic::rabbit_userid: {get_param: RabbitUserName}
        ironic::rabbit_password: {get_param: RabbitPassword}
        ironic::rabbit_port: {get_param: RabbitClientPort}
        ironic::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
      step_config: |
        include ::tripleo::profile::base::ironic
