heat_template_version: 2016-04-08

description: >
  Openstack Manila base service. Shared by manila-api/scheduler/share services

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  ManilaPassword:
    description: The password for the manila service account.
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the Manila Base service.
    value:
      service_name: manila_base
      config_settings:
        manila::rabbit_userid: {get_param: RabbitUserName}
        manila::rabbit_password: {get_param: RabbitPassword}
        manila::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        manila::rabbit_port: {get_param: RabbitClientPort}
        manila::debug: {get_param: Debug}
        manila::db::database_db_max_retries: -1
        manila::db::database_max_retries: -1
        manila::sql_connection:
          list_join:
          - ''
          - - {get_param: [EndpointMap, MysqlInternal, protocol]}
            - '://manila:'
            - {get_param: ManilaPassword}
            - '@'
            - {get_param: [EndpointMap, MysqlInternal, host]}
            - '/manila'
      service_config_settings:
        mysql:
          manila::db::mysql::password: {get_param: ManilaPassword}
          manila::db::mysql::user: manila
          manila::db::mysql::host: {get_param: [EndpointMap, MysqlInternal, host_nobrackets]}
          manila::db::mysql::dbname: manila
          manila::db::mysql::allowed_hosts:
            - '%'
            - "%{hiera('mysql_bind_host')}"
