heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Compute Nuage plugin

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaPassword:
    description: The password for the nova service account, used by nova-api.
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the Neutron Compute Nuage plugin
    value:
      service_name: neutron_compute_plugin_nuage
      config_settings:
        tripleo::profile::base::neutron::agents::nuage::nova_os_tenant_name: 'service'
        tripleo::profile::base::neutron::agents::nuage::nova_os_password: {get_param: NovaPassword}
        tripleo::profile::base::neutron::agents::nuage::nova_auth_ip: {get_param: [EndpointMap, KeystoneInternal, host]}
      step_config: |
        include ::tripleo::profile::base::neutron::agents::nuage
