heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Compute OVN agent

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  OVNDbHost:
    description: IP address on which the OVN DB servers are listening
    type: string
  OVNSouthboundServerPort:
    description: Port of the Southbound DB Server
    type: number
    default: 6642
  OVNTunnelEncapType:
    description: Tunnel encapsulation type
    type: string
    default: geneve


outputs:
  role_data:
    description: Role data for the Neutron Compute OVN agent
    value:
      service_name: neutron_compute_plugin_ovn
      config_settings:
        tripleo::profile::base::neutron::agents::ovn::ovn_db_host: {get_param: OVNDbHost}
        ovn::southbound::port: {get_param: OVNSouthboundServerPort}
        ovn::southbound::encap_type: {get_param: OVNTunnelEncapType}
        ovn::controller::ovn_encap_ip: {get_param: [ServiceNetMap, NeutronApiNetwork]}
      step_config: |
        include ::tripleo::profile::base::neutron::agents::ovn
