heat_template_version: 2016-04-08

description: >
  OpenStack Neutron L3 agent for DVR enabled compute nodes
  configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    type: string
    default: ''
  NeutronExternalNetworkBridge:
    description: Name of bridge used for external network traffic.
    type: string
    default: 'br-ex'
  MonitoringSubscriptionNeutronL3Dvr:
    default: 'overcloud-neutron-l3-dvr'
    type: string
  NeutronL3ComputeAgentLoggingSource:
    type: json
    default:
      tag: openstack.neutron.agent.l3-compute
      path: /var/log/neutron/l3-agent.log

resources:

  NeutronBase:
    type: ./neutron-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for DVR L3 Agent on Compute Nodes
    value:
      service_name: neutron_l3_compute_dvr
      monitoring_subscription: {get_param: MonitoringSubscriptionNeutronL3Dvr}
      logging_source: {get_param: NeutronL3ComputeAgentLoggingSource}
      logging_groups:
        - neutron
      config_settings:
        map_merge:
          - get_attr: [NeutronBase, role_data, config_settings]
          - neutron::agents::l3::external_network_bridge: {get_param: NeutronExternalNetworkBridge}
            neutron::agents::l3::agent_mode : 'dvr'
      step_config: |
        include tripleo::profile::base::neutron::l3
