heat_template_version: newton

description: >
  Installs bigswitch agent and enables the services

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json


outputs:
  role_data:
    description: Configure the bigswitch agent services
    value:
      service_name: neutron_bigswitch_agent
      step_config: |
        if hiera('step') >= 4 {
          include ::neutron::agents::bigswitch
        }
