heat_template_version: 2016-04-08

description: >
  OpenStack Neutron base service. Shared for all Neutron agents.

parameters:
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  NeutronDhcpAgentsPerNetwork:
    type: number
    default: 3
    description: The number of neutron dhcp agents to schedule per network
  NeutronCorePlugin:
    default: 'ml2'
    description: |
        The core plugin for Neutron. The value should be the entrypoint to be loaded
        from neutron.core_plugins namespace.
    type: string
  NeutronServicePlugins:
    default: "router,qos,trunk"
    description: |
        Comma-separated list of service plugin entrypoints to be loaded from the
        neutron.service_plugins namespace.
    type: comma_delimited_list
  Debug:
    type: string
    default: ''
    description: Set to True to enable debugging on all services.
  EnableConfigPurge:
    type: boolean
    default: true
    description: >
        Remove configuration that is not generated by TripleO. Setting
        to false may result in configuration remnants after updates/upgrades.
  NeutronGlobalPhysnetMtu:
    type: number
    default: 1496
    description: |
        MTU of the underlying physical network. Neutron uses this value to
        calculate MTU for all virtual network components. For flat and VLAN
        networks, neutron uses this value without modification. For overlay
        networks such as VXLAN, neutron automatically subtracts the overlay
        protocol overhead from this value. The default value of 1496 is
        currently in effect to compensate for some additional overhead when
        deploying with some network configurations (e.g. network isolation over
        single network interfaces)
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Role data for the Neutron base service.
    value:
      service_name: neutron_base
      config_settings:
        neutron::rabbit_password: {get_param: RabbitPassword}
        neutron::rabbit_user: {get_param: RabbitUserName}
        neutron::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        neutron::rabbit_port: {get_param: RabbitClientPort}
        neutron::dhcp_agents_per_network: {get_param: NeutronDhcpAgentsPerNetwork}
        neutron::core_plugin: {get_param: NeutronCorePlugin}
        neutron::service_plugins:
          str_replace:
            template: PLUGINS
            params:
              PLUGINS: {get_param: NeutronServicePlugins}
        neutron::debug: {get_param: Debug}
        neutron::purge_config: {get_param: EnableConfigPurge}
        neutron::allow_overlapping_ips: true
        neutron::rabbit_heartbeat_timeout_threshold: 60
        neutron::host: '"%{::fqdn}"'    #NOTE: extra quoting is needed
        neutron::db::database_db_max_retries: -1
        neutron::db::database_max_retries: -1
        neutron::global_physnet_mtu: {get_param: NeutronGlobalPhysnetMtu}
