heat_template_version: 2016-04-08

description: >
  OpenStack Nova API service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaWorkers:
    default: 0
    description: Number of workers for Nova API service.
    type: number

outputs:
  role_data:
    description: Role data for the Nova Metadata service.
    value:
      service_name: nova_metadata
      config_settings:
        nova::api::metadata_workers: {get_param: NovaWorkers}
        nova::api::metadata_listen: {get_param: [ServiceNetMap, NovaMetadataNetwork]}
      step_config: ""
