heat_template_version: 2016-04-08

description: >
  OpenStack Nova Scheduler service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaSchedulerAvailableFilters:
    default: []
    description: List of scheduler available filters
    type: comma_delimited_list
  NovaSchedulerDefaultFilters:
    type: comma_delimited_list
    default: []
    description: >
      An array of filters used by Nova to filter a node.These filters will be
      applied in the order they are listed, so place your most restrictive
      filters first to make the filtering process more efficient.
  MonitoringSubscriptionNovaScheduler:
    default: 'overcloud-nova-scheduler'
    type: string
  NovaSchedulerLoggingSource:
    type: json
    default:
      tag: openstack.nova.scheduler
      path: /var/log/nova/nova-scheduler.log

resources:
  NovaBase:
    type: ./nova-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Scheduler service.
    value:
      service_name: nova_scheduler
      monitoring_subscription: {get_param: MonitoringSubscriptionNovaScheduler}
      logging_source: {get_param: NovaSchedulerLoggingSource}
      logging_groups:
        - nova
      config_settings:
        map_merge:
          - get_attr: [NovaBase, role_data, config_settings]
          - nova::ram_allocation_ratio: '1.0'
            nova::scheduler::filter::scheduler_available_filters: {get_param: NovaSchedulerAvailableFilters}
            nova::scheduler::filter::scheduler_default_filters: {get_param: NovaSchedulerDefaultFilters}
      step_config: |
        include tripleo::profile::base::nova::scheduler
