heat_template_version: 2016-04-08

description: >
  OpenStack Sahara Engine service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MonitoringSubscriptionSaharaEngine:
    default: 'overcloud-sahara-engine'
    type: string
  SaharaEngineLoggingSource:
    type: json
    default:
      tag: openstack.sahara.engine
      path: /var/log/sahara/sahara-engine.log

resources:
  SaharaBase:
    type: ./sahara-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Sahara Engine role.
    value:
      service_name: sahara_engine
      monitoring_subscription: {get_param: MonitoringSubscriptionSaharaEngine}
      logging_source: {get_param: SaharaEngineLoggingSource}
      logging_groups:
        - sahara
      config_settings:
        map_merge:
          - get_attr: [SaharaBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::sahara::engine
