heat_template_version: 2016-04-08

description: >
  OpenStack Sahara base service. Shared for all Sahara services.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  SaharaPassword:
    description: The password for the sahara service account, used by sahara-api.
    type: string
    hidden: true
  Debug:
    type: string
    default: ''
    description: Set to True to enable debugging on all services.

outputs:
  role_data:
    description: Role data for the Sahara base service.
    value:
      service_name: sahara_base
      config_settings:
        sahara::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://sahara:'
              - {get_param: SaharaPassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/sahara'
              - '?bind_address='
              - "%{hiera('tripleo::profile::base::database::mysql::client_bind_address')}"
        sahara::rabbit_password: {get_param: RabbitPassword}
        sahara::rabbit_user: {get_param: RabbitUserName}
        sahara::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        sahara::rabbit_port: {get_param: RabbitClientPort}
        sahara::debug: {get_param: Debug}
        sahara::admin_password: {get_param: SaharaPassword}
        sahara::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri] }
        sahara::identity_uri: { get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix] }
        sahara::use_neutron: true
        sahara::plugins:
          - ambari
          - cdh
          - mapr
          - vanilla
          - spark
          - storm
        sahara::rpc_backend: rabbit
        sahara::admin_tenant_name: 'service'
        sahara::db::database_db_max_retries: -1
        sahara::db::database_max_retries: -1
