heat_template_version: 2016-04-08

description: >
  SNMP client configured with Puppet, to facilitate Ceilometer Hardware
  monitoring in the undercloud. This service is required to enable hardware
  monitoring.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  SnmpdReadonlyUserName:
    default: ro_snmp_user
    description: The user name for SNMPd with readonly rights running on all Overcloud nodes
    type: string
  SnmpdReadonlyUserPassword:
    description: The user password for SNMPd with readonly rights running on all Overcloud nodes
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the SNMP services
    value:
      service_name: snmp
      config_settings:
        tripleo::profile::base::snmp::snmpd_user: {get_param: SnmpdReadonlyUserName}
        tripleo::profile::base::snmp::snmpd_password: {get_param: SnmpdReadonlyUserPassword}
        tripleo.snmp.firewall_rules:
          '127 snmp':
            dport: 161
            proto: 'udp'
      step_config: |
        include ::tripleo::profile::base::snmp
