heat_template_version: 2016-04-08

description: >
  OpenStack Glance API service with Pacemaker configured with Puppet.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  GlanceFilePcmkDevice:
    default: ''
    description: >
      An exported storage device that should be mounted by Pacemaker
      as Glance storage. Effective when GlanceFilePcmkManage is true.
    type: string
  GlanceFilePcmkFstype:
    default: 'nfs'
    description: >
      Filesystem type for Pacemaker mount used as Glance storage.
      Effective when GlanceFilePcmkManage is true.
    type: string
  GlanceFilePcmkManage:
    default: false
    description: >
      Whether to make Glance file backend a mount managed by Pacemaker.
      Effective when GlanceBackend is 'file'.
    type: boolean
  GlanceFilePcmkOptions:
    default: ''
    description: >
      Mount options for Pacemaker mount used as Glance storage.
      Effective when GlanceFilePcmkManage is true.
    type: string

resources:

  GlanceApiBase:
    type: ../glance-api.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Glance role.
    value:
      service_name: glance_api
      monitoring_subscription: {get_attr: [GlanceApiBase, role_data, monitoring_subscription]}
      logging_source: {get_attr: [GlanceApiBase, role_data, logging_source]}
      logging_groups: {get_attr: [GlanceApiBase, role_data, logging_groups]}
      config_settings:
        map_merge:
          - get_attr: [GlanceApiBase, role_data, config_settings]
          - glance_file_pcmk_device: {get_param: GlanceFilePcmkDevice}
            glance_file_pcmk_fstype: {get_param: GlanceFilePcmkFstype}
            glance_file_pcmk_manage: {get_param: GlanceFilePcmkManage}
            glance_file_pcmk_options: {get_param: GlanceFilePcmkOptions}
            glance_file_pcmk_directory: '/var/lib/glance/images'
            glance::api::manage_service: false
            glance::api::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::glance
