heat_template_version: 2016-04-08

description: >
  Openstack Heat Engine service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  HeatEngineBase:
    type: ../heat-engine.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}


outputs:
  role_data:
    description: Role data for the Heat engine role.
    value:
      service_name: heat_engine
      monitoring_subscription: {get_attr: [HeatEngineBase, role_data, monitoring_subscription]}
      logging_source: {get_attr: [HeatEngineBase, role_data, logging_source]}
      logging_groups: {get_attr: [HeatEngineBase, role_data, logging_groups]}
      config_settings:
        map_merge:
          - get_attr: [HeatEngineBase, role_data, config_settings]
          - heat::engine::manage_service: false
            heat::engine::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::heat::engine
