heat_template_version: 2016-04-08

description: >
  OpenStack Keystone service with Pacemaker configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  KeystoneServiceBase:
    type: ../keystone.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Keystone pacemaker role.
    value:
      service_name: keystone
      monitoring_subscription: {get_attr: [KeystoneServiceBase, role_data, monitoring_subscription]}
      logging_source: {get_attr: [KeystoneServiceBase, role_data, logging_source]}
      logging_groups: {get_attr: [KeystoneServiceBase, role_data, logging_groups]}
      config_settings:
        map_merge:
          - get_attr: [KeystoneServiceBase, role_data, config_settings]
          - keystone::manage_service: false
            keystone::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::keystone
