heat_template_version: 2016-04-08

description: >
  Mecached service with Pacemaker configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  MemcachedServiceBase:
    type: ../memcached.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Memcached pacemaker role.
    value:
      service_name: memcached
      monitoring_subscription: {get_attr: [MemcachedServiceBase, role_data, monitoring_subscription]}
      config_settings:
        map_merge:
          - get_attr: [MemcachedServiceBase, role_data, config_settings]
          - memcached::service_manage: false
      step_config: |
        include ::tripleo::profile::pacemaker::memcached
