heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Server with Pacemaker configured with Puppet.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NeutronL3HA:
    default: true
    description: Whether to enable HA for virtual routers
    type: boolean

resources:

  NeutronServerBase:
    type: ../neutron-server.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Neutron Server.
    value:
      service_name: neutron_server
      monitoring_subscription: {get_attr: [NeutronServerBase, role_data, monitoring_subscription]}
      config_settings:
        map_merge:
          - get_attr: [NeutronServerBase, role_data, config_settings]
          - neutron::server::enabled: false
            neutron::server::manage_service: false
            neutron::server::l3_ha: {get_param: NeutronL3HA}
      step_config: |
        include ::tripleo::profile::pacemaker::neutron::server
