heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Midonet with Pacemaker configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronMidonetBase:
    type: ../neutron-midonet.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Neutron Midonet plugin.
    value:
      service_name: neutron_midonet
      monitoring_subscription: {get_attr: [NeutronMidonetBase, role_data, monitoring_subscription]}
      config_settings:
        map_merge:
          - get_attr: [NeutronMidonetBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::pacemaker::neutron::plugins::midonet
