heat_template_version: 2014-10-16

description: >
  Software-config for performing aodh data migration

parameters:
  servers:
    type: json
  input_values:
    type: json
    description: input values for the software deployments
resources:

  AodhMysqlMigrationScriptConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: aodh_data_migration.sh}

  AodhMysqlMigrationScriptDeployment:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: [servers, Controller]}
      config: {get_resource: AodhMysqlMigrationScriptConfig}
      input_values: {get_param: input_values}
