heat_template_version: 2014-10-16
description: 'Post-Puppet restart config for Pacemaker deployments'

parameters:
  servers:
    type: json
  input_values:
     type: json
     description: input values for the software deployments

resources:

  ControllerPostPuppetRestartConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        list_join:
        - ''
        - - get_file: pacemaker_common_functions.sh
          - get_file: pacemaker_resource_restart.sh

  ControllerPostPuppetRestartDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerPostPuppetRestartConfig}
      input_values: {get_param: input_values}
