heat_template_version: 2016-04-08

description: >
  Contrail Config service deployment using puppet, this YAML file
  creates the interface between the HOT template
  and the puppet manifest that actually installs
  and configures Contrail Config.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ContrailConfigIfmapServerIp:
    description: Ifmap server ip address
    type: string
  ContrailConfigIfmapUserName:
    description: Ifmap user name
    type: string
  ContrailConfigIfmapUserPassword:
    description: Ifmap user password
    type: string
  ContrailConfigRabbitServerIp:
    description: RabbitMq server ip address
    type: string
  ContrailConfigRedisServerIp:
    description: Redis server ip address
    type: string
  ContrailConfigListenAddress:
    default: '0.0.0.0'
    description: IP address Config API is listening on
    type: string
  ContrailConfigListenPort:
    default: 8082
    description: Port Config API is listening on
    type: number

resources:
  ContrailBase:
    type: ./contrail-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role Contrail Config using composable services.
    value:
      service_name: contrail_config
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - contrail::config::ifmap_password: {get_param: ContrailConfigIfmapUserPassword}
            contrail::config::ifmap_server_ip: {get_param: ContrailConfigIfmapServerIp}
            contrail::config::ifmap_username: {get_param: ContrailConfigIfmapUserName}
            contrail::config::listen_ip_address: {get_param: ContrailConfigListenAddress}
            contrail::config::listen_port: {get_param: ContrailConfigListenPort}
            contrail::config::rabbit_server: {get_param: ContrailConfigRabbitServerIp}
            contrail::config::redis_server: {get_param: ContrailConfigRedisServerIp}
      step_config: |
        include ::tripleo::network::contrail::config
