heat_template_version: 2014-10-16

parameters:
  Hostname:
    type: string

resources:

  ControlPlanePort:
    type: OS::Neutron::Port
    properties:
      network: ctlplane
      name:
        list_join:
          - '-'
          - - {get_param: Hostname}
            - ctlplane
            - port
      replacement_policy: AUTO

outputs:
  ip_address:
    value: {get_attr: [ControlPlanePort, fixed_ips, 0, ip_address]}
