heat_template_version: 2014-10-16
parameters:
  user_data_format:
    type: string
    default: SOFTWARE_CONFIG

resources:
  # We just need something which returns a unique ID, but we can't
  # use RandomString because RefId returns the value, not the physical
  # resource ID, SoftwareConfig should work as it returns a UUID
  deployed-server-config:
    type: OS::Heat::SoftwareConfig

outputs:
  # FIXME(shardy) this is needed because TemplateResource returns an
  # ARN not a UUID, which overflows the Deployment server_id column..
  user_data_format:
    value: SOFTWARE_CONFIG
  OS::stack_id:
    value: {get_resource: deployed-server-config}


