heat_template_version: 2016-10-14
description: 'All Hosts Config'

parameters:
  hosts:
    type: comma_delimited_list

resources:

  hostsConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hosts:
          list_join:
          - "\n"
          - {get_param: hosts}

outputs:
  config_id:
    description: The ID of the hostsConfigImpl resource.
    value:
      {get_resource: hostsConfigImpl}
  hosts_entries:
    description: |
      The content that should be appended to your /etc/hosts if you want to get
      hostname-based access to the deployed nodes (useful for testing without
      setting up a DNS).
    value: {get_attr: [hostsConfigImpl, config, hosts]}
