heat_template_version: 2015-04-30

description: >
  OpenStack Libvirt Service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerLibvirtImage:
    description: image
    default: 'centos-binary-libvirt'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaLibvirtBase:
    type: ../../puppet/services/nova-libvirt.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Libvirt service.
    value:
      config_settings: {get_attr: [NovaLibvirtBase, role_data, config_settings]}
      step_config: {get_attr: [NovaLibvirtBase, role_data, step_config]}
      puppet_tags: nova_config
      docker_config:
        step_1:
          nova_libvirt:
            image:
              list_join:
                - '/'
                - [ {get_param: DockerNamespace}, {get_param: DockerLibvirtImage} ]
            net: host
            pid: host
            privileged: true
            restart: always
            volumes:
              - /var/lib/etc-data/json-config/nova-libvirt.json:/var/lib/kolla/config_files/config.json
              - /var/lib/etc-data/libvirt/libvirtd.conf:/var/lib/kolla/config_files/libvirtd.conf
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
              - /dev:/dev
              - /sys/fs/cgroup:/sys/fs/cgroup
              - logs:/var/log/kolla/
              - libvirtd:/var/lib/libvirt
              - nova_compute:/var/lib/nova/
              - nova_libvirt_qemu:/etc/libvirt/qemu
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
        step_2: {}
