heat_template_version: 2016-04-08

description: >
  NTP service deployment using puppet, this YAML file
  creates the interface between the HOT template
  and the puppet manifest that actually installs
  and configure NTP.

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NtpServer:
    default: []
    description: NTP servers
    type: comma_delimited_list

outputs:
  role_data:
    description: Role ntp using composable services.
    value:
      service_name: ntp
      config_settings:
        ntp::servers: {get_param: NtpServer}
        tripleo.ntp.firewall_rules:
          '105 ntp':
            dport: 123
            proto: udp
      step_config: |
        include ::tripleo::profile::base::time::ntp
