heat_template_version: 2016-04-08

description: >
  Composable Timezone service

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  TimeZone:
    default: 'UTC'
    description: The timezone to be set on the overcloud.
    type: string

outputs:
  role_data:
    description: Timezone role using composable services.
    value:
      service_name: timezone
      config_settings:
        timezone::timezone: {get_param: TimeZone}
      step_config: |
        include ::timezone
